### ISSUE TITLE
UX interviews

### ISSUE THREAD

**Issue by KirstieJane** [dat-land/project-trackbook#1]
@marek-kultys has built a prototype demo of our idea and we're going to solicit feedback on it with three people who are physically located at the eLife sprint.

The UX interview template is at: https://hackmd.io/7_LQF3cbTIe-gBv18JX51Q

**Comment by joehand** [comment]
For posterity, the hackmd file:

<details>

# Project Trackbook UX Interviews

***User interviews and prototype demo feedback***

**Administered at:** eLife Innovation Sprint
**On:** 11th May 2018

---

## INTERVIEW 1

Hi, thank you for taking part in our Project Trackbook interviews!!

We're going to ask you a few questions about yourself, and then show you a prototype we've developed for our idea. We're really interested in any feedback you can give - positive or negative!

We're asking for your feedback early so that we can build something you would actually use :smile:

Let's start by asking a few questions about you:

1. What is your name. Do you consent to us using this information publicly?

> Delwyn - yes.

2. What is your job? Please interpret this very broadly - you can define yourself however you want.

> Researcher - neurobiology. Electrophysiology, Ca++ imaging. Wet lab - patch clamping.

What we want to achieve for the Project Trackbook is a lab book for the modern age. Our two priorities are 1) secure and easy file sharing with collaborators, and 2) version control.

As a key side effect of these priorities we want to also facilitate sharing of all the information a re-user would need to understand your project *without you being there*. Therefore we want to prioritise data management and metadata capture alongside the original and processed data files.

3. What does useful data sharing meant to you? Would you value this sort of tool? Which aspects of our description resonate most strongly with you?

> Any tool that makes data sharing more easy would be VERY valuable.

> Integrating the raw file with the parameters - temperature, time, date, etc. Also integrating your own comments on top - annotations - your thoughts. Putting those together in a central place would be really valuable.

> *what* is being recorded, *all the other notes*, *your insights*.

3. What tools do you currently use to achieve those goals?

> Non electronic lab book - written everything down.
> Very difficult to share.

> An electronic one would be really useful - easier to search, easier to edit, easier to filter the data you've collected. Can be linked directly to the analysis, being able to back up.

> Traditional one completely out of date.

> Data I use are images and timeseries - around a few MB per file - not too big.

4. What tools do you currently use to share files with collaborators?
 
University hosted cloud based system. Able to share outside of university too.

Not easy to sync updates - would have to do individually. Would have been great to be able to have synced changes from different computers.

Manual updates are a pain in the bum.

Not allowed to use Dropbox.

Had a server to backup. Technically would be allowed to give access but not all that helpful to outside collaborators.
 
5. How do you manage data within your research group?

Indidivual researchers would back up their individual projects to the institutional server.

Rare to share raw data.

Working on different projects. No standards in the research group.

Towards the end of the project I was working on building up some better practises.

6. What improvements or changes would you make to your current workflow? What limitations or bloskers do you encounter and/or what do you want to be able to do. 

Want better integration of everything you're recording and the metadata. In ONE place. In digital form. Automatically backed up. Don't want to have to worry about all these data management steps - protect the researcher's time to do "actual research".

Would be really nice to be able to take notes WHILE doing the experiment - so mobile friendly or ipad friendly so you can add quick notes would be great.


Let me show you the prototype we've developed. 

As we go through the demo, please speak out loud what you're thinking (if you can!) and let us know what makes sense and what questions you have.

The scenario we're imagining: A PhD student wants to share a figure they've created with their supervisor.

This file can not be shared through a cloud service because there is sensitive data involved in the figure. The student wants to keep track of the versions of the file as it develops.

[INSERT PROTOTYPE DEMO HERE!]

We're using the Beaker Browser and we're going to navigate to the project we've made.

> Can you add a button to make it easier to access?
> A: Maybe could be shared to favourites so you have it bookmarked for future use.

Peer to peer network - NOTE: need to explain this

> Project overview pages looks great!

On the right are your files for a project and on the left are your metadata notes.

> Really nice to START a project this way - document your goals, ideas, hypotheses

> Is this the raw data or the analysis files?
> Looks like you are linking up all the different files that you've put in the folder - raw and analysis together.

When you change a file in the analysis folder, there is a prompt to change the description for the associated metadata.

> Really neat - very nice.
> If I don't interact with the prompt to update the metadata then I can disregard it.
> For example if I *don't* have to change what I've written.

> I'd like the flexibility of adding my own sections on the left hand side - would be nice to be able to set up my own structure.

We're going to change the file and summarise what has happened, then commit that files.

> Looks really easy - feels very intuitive.

You can share this now by sending the hash, or by adding their emails to a box.

> Woah, Charles Darwin is interested! NICE!
> I'd expect that THE RECEIVER would now be able to interact with these files in exactly the same way that I can.

> Can I communicate with the collaborators? 
> I'm hesitant on whether we'd want that - the version control will anotate what my thought process is/was. But maybe there could be a discussion board - kinda like a private messaging section - to be able to send comments/thoughts/updates back and forth.
> Called something like discussion - near the box for who you've shared everything with.
> Like a slack integration but it doesn't have to be SLACK per se - could be something else!

> You'd be able to remove the files, right? 

Do you have any other hopes & dreams?

> Would it be possible to link it up to GitHub?

You can have a .git folder in one of the folders - that can sync up super easily.

> Would be great to have a raw data folder in here, and separate folders for processed data, or analyses, or figures, or code, or notes etc.
> Important to be able to pull all these possible data types into the same folder structure to keep it all together.

> I'd love to be able to link up files together - focusing on the provenance of the processing - could you click on a processed image and have it highlight which 

> Really valuable to have some standards - not a fan of forcing everyone to fit in the same box. But SOME standards from the beginning is really helpful!

> This idea looks great for a non-confident command line user - there's a lot of things to learn when you're a new PhD student and helping people to do version control without adding too much onboarding 


## INTERVIEW 2

***User interviews and prototype demo feedback***

**Administered at:** eLife Innovation Sprint
**On:** 11th May 2018

---

Hi, thank you for taking part in our Project Trackbook interviews!!

We're going to ask you a few questions about yourself, and then show you a prototype we've developed for our idea. We're really interested in any feedback you can give - positive or negative!

We're asking for your feedback early so that we can build something you would actually use :smile:

Let's start by asking a few questions about you:

1. What is your name. Do you consent to us using this information publicly?

> Daniela - yes!

2. What is your job? Please interpret this very broadly - you can define yourself however you want.

> PhD student in neuroscience. Set up experiments using electrophysiology to study the auditory system - these last 6-7 hours. There's also some data that we'd collect that will be analysed that evening - spike sorting etc.

>Other days are analysis or prepwork.


What we want to achieve for the Project Trackbook is a lab book for the modern age. Our two priorities are 1) secure and easy file sharing with collaborators, and 2) version control.

As a key side effect of these priorities we want to also facilitate sharing of all the information a re-user would need to understand your project *without you being there*. Therefore we want to prioritise data management and metadata capture alongside the original and processed data files.

3. What does useful data sharing meant to you? Would you value this sort of tool? Which aspects of our description resonate most strongly with you?

> I really like the capture of the metadata & comments.

> I can imagine that for a human lab it's really really important to stay super secure. It needs to be secure. There are quite a few tools that we're not allowed to use because they're hosted by 3rd party servers (eg: google docs, dropbox etc).

4. What tools do you currently use to share files with collaborators?

> Code - git & bitbucket. Open source projects are in github and the closed projects are on bitbucket. Many of these "closed" projects are old scripts that are very specfic for work in the lab.

> To share files we use slack within the lab. For example in specific project channels.

5. How do you manage data within your research group?

> My PI is quite tech savy - we have a local server with a database and we log in and track the ID of the experiment and the time and date. Then there are prompts to ensure that we write down the important things that we need to record.

> I also take notes on paper - I personally like to be able to draw some of the concepts. Not everyone does it. I also like to have a history of everything that I've been doing. To be honest, I think it's partly because this was how I was trained. I just find it easier to flick through the pages of the lab book to be able to easily go through the 

> The main database captures really valuable metadata in a standard form. It is possible to upload images that I've taken from the experiment etc.


6. What improvements or changes would you make to your current workflow? What limitations or bloskers do you encounter and/or what do you want to be able to do. 

> I think it would be great to be able to customise the main database. I'd like to be able to set it up the way that *I* would like to interact with it.

Let me show you the prototype we've developed. 

As we go through the demo, please speak out loud what you're thinking (if you can!) and let us know what makes sense and what questions you have.

The scenario we're imagining: A PhD student wants to share a figure they've created with their supervisor.

This file can not be shared through a cloud service because there is sensitive data involved in the figure. The student wants to keep track of the versions of the file as it develops.

[INSERT PROTOTYPE DEMO HERE!]

We'll open the Beaker Browser and navigate to the specific hash link for your project.

You can see on the left the 

> This looks like a scaffold for a paper. Get all your framing for a project set up from the beginning.
> I think it would be really valuable to have that scaffold from the

> DANIELLE: integrate with the eLife reproducible paper stack
> 
\project space - information about project, files in folders organized by the user, plus version information

\these are files related to this project, \daniela wants high level info on the left and low level on the right

\adding a file

adding a file, not tracked yet, 

what does it mean?

she doesn't know what 'not tracked' means - it's not being assigned an id for version control?

yes, she does know what it means

\the warning in the descriptions section, updates in that section, user can edit this section to address new the files

committing the changes added here, committing to version history

Sumarize what has been changed

is it required to add a comment? it should many people are being required, must have required comments

commit changes

total revisions - is this a revision by everyone who has access or by you? all revisions done by anyone. \unless it it only you who has shared the project

\now to add new users to share your file, send them an email with the hash or add email addresses to send the key

make revisions and changes?

\do they need to accept in order to become a collaborator? Yes, she wants them to confirm their addition

\once they have been added they know the hash key and can access the data. two days later.... you access the project again and see a revision

\now this thing you collaborator adds is tracked by the version history

This can be any type of files? any files in any folder straucture that you want, if it was a funky file type, an illustrator file type, it would ask how you want to open it

every project has the same layout, but you can add as many panels as you want. these panels would be long, so first few displayed plus click to expand


</details>
