### ISSUE TITLE
Hackmd project notes

### ISSUE THREAD

**Issue by daniellecrobinson** [dat-land/project-trackbook#2]
Here are the notes we have made during the eLife sprint https://hackmd.io/pYC614GXQM6YHBKkrkD_NA?view

**Comment by joehand** [comment]
For posterity, the hackmd file:

<details>
# project trackbook - elife sprint notes

**Description:** Open lab notebook giving researchers an interface to securely share and version control files in decentralized network.


## Resources & Links

* https://github.com/dat-land/project-trackbook

### Related Tech

* http://beakerbrowser.com/
* https://datproject.org/
* (Dat-based CMS) http://enoki.site/

## Project Plan

### Thursday

**GOAL: Create alpha MVP to demonstrate functionality. Design final user experience and Friday project plan.** 

* Team Alpha - Develop very basic MVP for how CMS, dat, and everything come together
* Team Omega - User research and stories, prototype design

* **1:30 - 4pm** - Teams work on teamwork!
* **At 4pm** - Teams get together 
* **4pm - 4:30** - Teams review group work (15min each)
* **4:30 - 5pm** - Brainstorm final project goal
* **5pm - 5:30** - Develop Friday project plan

#### UX Team
**What are our users?**
PI
Student
Other scholar

**List of basic tasks:**

1. Upload a file, a draft figure in ppt
2. Share with colleagues and boss
3. Get feedback

**Focusing on one user -->**

Assumptions: I work with sensitive data that can not be shared outside my research group until a certain point. 


1. Install Beaker
2. Create a personal site
3. Create a new project folder 
4. Add files to that project folder

---

1. I open beaker browser and open my personal offline, private trackpad site
2. Add a file to a project on my site, it will then be tracked by Dat
3. I update metadata that describes changes
4. I make a new event in version history
5. I copy the secure hash to share
6. I share the secure hash of the project I am working on
7. I receive feedback from colleagues on figure
8. I access version history to find a figure from 2 days ago
9. I edit the historical file and create new version
10. I update metadata that describes changes
11. I make a new event in version history
12. They are notified that I have updates
13. They view the updates files











### Friday

**_TODO_**


### UX Interviews

Hi, thank you for taking part in our Project Trackbook interviews!!

We're going to ask you a few questions about yourself, and then show you a prototype we've developed for our idea. We're really interested in any feedback you can give - positive or negative!

We're asking for your feedback early so that we can build something you would actually use :smile:

Let's start by asking a few questions about you:

1. What is your name. Do you consent to us using this information publicly?

2. What is your job? Please interpret this very broadly - you can define yourself however you want.

What we want to achieve for the Project Trackbook is a lab book for the modern age. Our two priorities are 1) secure and easy file sharing with collaborators, and 2) version control.

As a key side effect of these priorities we want to also facilitate sharing of all the information a re-user would need to understand your project *without you being there*. Therefore we want to prioritise data management and metadata capture alongside the original and processed data files.

3. Does this sound useful to you? Would you value this sort of tool? Which aspects of our description resonate most strongly with you?

4. What tools do you currently use to share files with collaborators?
 
5. How do you manage data within your research group?

6. What improvements or changes would you make to your current workflow? What limitations or bloskers do you encounter and/or what do you want to be able to do. 

Let me show you the prototype we've developed. 

As we go through the demo, please speak out loud what you're thinking (if you can!) and let us know what makes sense and what questions you have.

The scenario we're imagining: A PhD student wants to share a figure they've created with their supervisor.

This file can not be shared through a cloud service because there is sensitive data involved in the figure. The student wants to keep track of the versions of the file as it develops.

[INSERT PROTOTYPE DEMO HERE!]



## Random Notes



</details>

**Comment by KirstieJane** [comment]
Aren’t you (@joehand) supposed to be having a day off??

Thank you for the clean up though! And enjoy [cream teas in Grantchester](http://www.theorchardteagarden.co.uk)!
